# Generated by Django 2.2.6 on 2019-11-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrik',
            fields=[
                ('id_distrik', models.AutoField(primary_key=True, serialize=False)),
                ('nama_distrik', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('id_distrik',),
            },
        ),
        migrations.CreateModel(
            name='Kampung',
            fields=[
                ('id_kampung', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kampung', models.CharField(max_length=100)),
                ('distrik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasarikan.Distrik')),
            ],
            options={
                'ordering': ('id_kampung',),
            },
        ),
    ]
